######################################################################
env_name: kitchen-mixed-v0

# future action forecasts
action_dim: 9
horizon_steps: 4
act_steps: 4

# observation history
obs_dim: 60
cond_steps: 1
###################################################################

defaults:
  - _self_
hydra:
  run:
    dir: ${logdir}
_target_: agent.finetune.grpo.train_grpo_drifting_agent.TrainGRPODriftingAgent
name: ${env_name}_grpo_drifting_unet1d_ta${horizon_steps}
logdir: ${oc.env:REINFLOW_LOG_DIR}/gym/finetune/${env_name}_grpo_drifting_unet1d_ta${horizon_steps}/${now:%Y-%m-%d}_${now:%H-%M-%S}_seed${seed}
base_policy_path:       # specify path to pre-trained drifting model
normalization_path: ${oc.env:REINFLOW_DATA_DIR}/gym/${env_name}/normalization.npz

# GRPO parameters
batch_size: 256
seed: 42
device: cuda:0
n_train_itr: 301
n_steps: 200
log_freq: 5
save_model_freq: 50

train:
  group_size: 16
  grpo_lr: 1e-5
  update_epochs: 4
  grpo_batch_size: 256
  kl_beta: 0.05
  kl_beta_min: 0.001
  kl_beta_decay: 0.995
  use_homogeneous_reset: true
  verbose: true

wandb:
  entity: ${oc.env:REINFLOW_WANDB_ENTITY}
  project: DM1-gym-${env_name}-finetune
  run: ${now:%Y-%m-%d}_${now:%H-%M-%S}_${name}_grpo
  offline_mode: false

model:
  _target_: model.drifting.ft_grpo.grpodrifting.GRPODrifting
  actor_policy_path: ${base_policy_path}
  device: ${device}
  epsilon: 0.2
  beta: 0.05

env:
  n_envs: 40
  name: ${env_name}
  max_episode_steps: 280
  reset_at_iteration: false
  save_video: false
  best_reward_threshold_for_success: 4.0
  wrappers:
    mujoco_locomotion_lowdim:
      normalization_path: ${normalization_path}
    multi_step:
      n_obs_steps: ${cond_steps}
      n_action_steps: ${act_steps}
      max_episode_steps: ${env.max_episode_steps}
      reset_within_step: true
