######################################################################
env_name: kitchen-mixed-v0

# future action forecasts
action_dim: 9
horizon_steps: 4
act_steps: 4

# observation history
obs_dim: 60
cond_steps: 1
###################################################################

defaults:
  - _self_
hydra:
  run:
    dir: ${logdir}
_target_: agent.eval.eval_drifting_agent.EvalDriftingAgent

name: ${env_name}_eval_drifting_transformer_ta${horizon_steps}
logdir: ${oc.env:REINFLOW_LOG_DIR}/gym-eval/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
base_policy_path:
normalization_path: ${oc.env:REINFLOW_DATA_DIR}/gym/${env_name}/normalization.npz

seed: 42
device: cuda:2

denoising_steps: 1
denoising_step_list: [1]
load_ema: true


n_steps: 500  # each episode can take maximum (max_episode_steps / act_steps, =250 right now) steps but may finish earlier in gym.
              # We only count episodes finished within n_steps for evaluation.
render_num: 0 # 0  positive if save_video, otherwise 0.

env:
  n_envs: 40
  name: ${env_name}
  max_episode_steps: 280
  reset_at_iteration: false
  save_video: false
  best_reward_threshold_for_success: 4.0
  wrappers:
    mujoco_locomotion_lowdim:
      normalization_path: ${normalization_path}
    multi_step:
      n_obs_steps: ${cond_steps}
      n_action_steps: ${act_steps}
      max_episode_steps: ${env.max_episode_steps}
      reset_within_step: true
model:
  _target_: model.drifting.drifting.DriftingPolicy
  network:
    _target_: model.drifting.backbone.transformer_for_drifting.TransformerForDrifting
    input_dim: ${action_dim}
    output_dim: ${action_dim}
    horizon: ${horizon_steps}
    n_obs_steps: ${cond_steps}
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    n_layer: 4
    n_head: 4
    n_emb: 256
    p_drop_emb: 0.1
    p_drop_attn: 0.1
    causal_attn: true
    time_as_cond: false
    obs_as_cond: true
  device: ${device}
  horizon_steps: ${horizon_steps}
  action_dim: ${action_dim}
  act_min: -1
  act_max: 1
  obs_dim: ${obs_dim}
  max_denoising_steps: ${denoising_steps}
  seed: ${seed}
  drift_coef: 1.0
  neg_drift_coef: 0.5
  mask_self: true
  bandwidth: 1.0
