######################################################################
# environment and task
env_suite: gym
env: Humanoid-medium-v3

# future action forecasts
action_dim: 17
horizon_steps: 4

# observation history
obs_dim: 376
cond_steps: 1
###################################################################

defaults:
  - _self_
hydra:
  run:
    dir: ${logdir}
_target_: agent.pretrain.train_meanflow_agent.TrainMeanFlowAgent
name: ${env}_pre_meanflow_mlp_ta${horizon_steps}
logdir: ${oc.env:REINFLOW_LOG_DIR}/gym/pretrain/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
train_dataset_path: ${oc.env:REINFLOW_DATA_DIR}/gym/${env}/train.npz
normalization_path: ${oc.env:REINFLOW_DATA_DIR}/gym/${env}/normalization.npz
use_d4rl_dataset: True

# MeanFlow parameters
flow_ratio: 0.5  # ratio of samples using flow consistency (r=t)
gamma: 0.5       # parameter for adaptive L2 loss
c: 1e-3          # stability constant for adaptive loss

batch_size: 128
seed: 42
device: cuda:0
test_in_mujoco: True
auto_resume: True  # automatically resume from the latest checkpoint if available
max_n_episodes: -1
wandb:
  entity: ${oc.env:REINFLOW_WANDB_ENTITY}
  project: DM1-gym-${env}-pretrain
  run: ${now:%H-%M-%S}_${name}

train:
  n_epochs: 100
  batch_size: ${batch_size}
  learning_rate: 5e-4
  weight_decay: 1e-6
  lr_scheduler:
    first_cycle_steps: 100
    warmup_steps: 10
    min_lr: 5e-5
  save_model_freq: 20
  test_freq: 20

model:
  _target_: model.flow.meanflow.MeanFlow
  network:
    _target_: model.flow.mlp_meanflow.MeanFlowMLP
    action_dim: ${action_dim}
    horizon_steps: ${horizon_steps}
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    time_dim: 16
    r_embedding_dim: 16
    mlp_dims: [768, 768, 768]
    cond_mlp_dims: [128, 32]
    activation_type: Mish
    out_activation_type: Identity
    use_layernorm: false
    residual_style: true
  device: ${device}
  horizon_steps: ${horizon_steps}
  action_dim: ${action_dim}
  act_min: -1
  act_max: 1
  obs_dim: ${obs_dim}
  max_denoising_steps: 5  # MeanFlow designed for 1-step generation
  seed: ${seed}
  flow_ratio: ${flow_ratio}
  gamma: ${gamma}
  c: ${c}
  sample_t_type: uniform
  use_adaptive_loss: true

ema:
  decay: 0.995

train_dataset:
  _target_: agent.dataset.sequence.StitchedSequenceDataset
  dataset_path: ${train_dataset_path}
  horizon_steps: ${horizon_steps}
  cond_steps: ${cond_steps}
  device: ${device}
  max_n_episodes: ${max_n_episodes}
