######################################################################
# environment and task
env_suite: gym
env: walker2d-medium-v2

# future action forecasts
action_dim: 6
horizon_steps: 4

# observation history
obs_dim: 17
cond_steps: 1

# dispersive loss naming
dispersive_weight_name: "0p5"
dispersive_temp_name: "0p5"
dispersive_type_name: "infnce"
###################################################################

defaults:
  - _self_
hydra:
  run:
    dir: ${logdir}
_target_: agent.pretrain.train_improved_meanflow_agent.TrainImprovedMeanFlowDispersiveAgent
name: ${env}_pre_improved_meanflow_dispersive_mlp_ta${horizon_steps}_${dispersive_type_name}_d${dispersive_weight_name}_t${dispersive_temp_name}
logdir: ${oc.env:REINFLOW_LOG_DIR}/gym/pretrain/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
train_dataset_path: ${oc.env:REINFLOW_DATA_DIR}/gym/${env}/train.npz
normalization_path: ${oc.env:REINFLOW_DATA_DIR}/gym/${env}/normalization.npz
use_d4rl_dataset: True

# iMF parameters
flow_ratio: 0.5
gamma: 0.5
c: 1e-3

batch_size: 128  # aligned with other MeanFlow variants
seed: 42
device: cuda:0
test_in_mujoco: True
auto_resume: True  # automatically resume from the latest checkpoint if available
max_n_episodes: -1
wandb:
  entity: ${oc.env:REINFLOW_WANDB_ENTITY}
  project: DM1-gym-${env}-pretrain
  run: ${now:%H-%M-%S}_${name}

train:
  n_epochs: 80  # aligned with MeanFlow
  batch_size: ${batch_size}
  learning_rate: 1e-3  # aligned with MeanFlow
  weight_decay: 1e-6
  lr_scheduler:
    first_cycle_steps: 80  # aligned with n_epochs
    warmup_steps: 10
    min_lr: 1e-4
  save_model_freq: 20
  test_freq: 20

model:
  _target_: model.flow.improved_meanflow.ImprovedMeanFlowDispersive
  network:
    _target_: model.flow.mlp_meanflow.MeanFlowMLP
    action_dim: ${action_dim}
    horizon_steps: ${horizon_steps}
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    time_dim: 16
    r_embedding_dim: 16
    mlp_dims: [512, 512, 512]
    cond_mlp_dims: [64, 16]
    activation_type: Mish
    out_activation_type: Identity
    use_layernorm: false
    residual_style: true
  device: ${device}
  horizon_steps: ${horizon_steps}
  action_dim: ${action_dim}
  act_min: -1
  act_max: 1
  obs_dim: ${obs_dim}
  max_denoising_steps: 5
  seed: ${seed}
  flow_ratio: ${flow_ratio}
  gamma: ${gamma}
  c: ${c}
  sample_t_type: lognormal
  use_adaptive_loss: false
  use_auxiliary_head: false
  dispersive_loss_weight: 0.5
  dispersive_loss_type: "infonce_l2"
  dispersive_temperature: 0.5
  dispersive_margin: 1.0
  apply_dispersive_to_embeddings: true

ema:
  decay: 0.995

train_dataset:
  _target_: agent.dataset.sequence.StitchedSequenceDataset
  dataset_path: ${train_dataset_path}
  horizon_steps: ${horizon_steps}
  cond_steps: ${cond_steps}
  device: ${device}
  max_n_episodes: ${max_n_episodes}
