######################################################################
env_name: avoiding-m5
mode: d57_r12 # M2, desired modes 5 and 7, required modes 1 and 2
obs_dim: 4
action_dim: 2
horizon_steps: 4
act_steps: 4
cond_steps: 1
###################################################################

defaults:
  - _self_
hydra:
  run:
    dir: ${logdir}
_target_: agent.finetune.grpo.train_grpo_drifting_agent.TrainGRPODriftingAgent
name: ${env_name}_m2_ft_grpo_drifting_transformer_ta${horizon_steps}
logdir: ${oc.env:REINFLOW_LOG_DIR}/d3il-finetune/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_seed${seed}
base_policy_path:

# GRPO parameters
batch_size: 256
seed: 42
device: cuda:0
n_train_itr: 51
n_steps: 100
log_freq: 5
save_model_freq: 10

train:
  group_size: 16
  grpo_lr: 1e-5
  update_epochs: 4
  grpo_batch_size: 256
  kl_beta: 0.05
  kl_beta_min: 0.001
  kl_beta_decay: 0.995
  use_homogeneous_reset: true
  verbose: true

wandb:
  entity: ${oc.env:REINFLOW_WANDB_ENTITY}
  project: DM1-d3il-${env_name}-finetune
  run: ${now:%Y-%m-%d}_${now:%H-%M-%S}_${name}_grpo
  offline_mode: false

model:
  _target_: model.drifting.ft_grpo.grpodrifting.GRPODrifting
  actor_policy_path: ${base_policy_path}
  device: ${device}
  epsilon: 0.2
  beta: 0.05

env:
  n_envs: 50
  name: ${env_name}
  max_episode_steps: 100
  reset_at_iteration: false
  save_video: false
  best_reward_threshold_for_success: 2
  wrappers:
    d3il_lowdim:
      normalization_path: ${oc.env:REINFLOW_DATA_DIR}/d3il/avoid_m2/normalization.npz
      mode: ${mode}
    multi_step:
      n_obs_steps: ${cond_steps}
      n_action_steps: ${act_steps}
      max_episode_steps: ${env.max_episode_steps}
      reset_within_step: true
