###################################
env_suite: robomimic
env_name: transport

obs_dim: 18  # two robots
cond_steps: 1
img_cond_steps: 1

action_dim: 14  # two robots
horizon_steps: 8  # match pretrain
act_steps: 8  # match pretrain
###################################
defaults:
  - _self_
hydra:
  run:
    dir: ${logdir}
_target_: agent.finetune.reinflow.train_ppo_meanflow_img_agent.TrainPPOImgMeanFlowAgent
name: ${env_name}_ft_meanflow_mlp_img_ta${horizon_steps}_td${denoising_steps}_tdf${ft_denoising_steps}_seed${seed}
logdir: ${oc.env:REINFLOW_LOG_DIR}/robomimic/finetune/${env_name}_ft_meanflow_mlp_img_ta${horizon_steps}_td${denoising_steps}_tdf${ft_denoising_steps}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
base_policy_path: 
resume_path: null
robomimic_env_cfg_path: cfg/robomimic/env_meta/${env_name}-img.json
normalization_path: ${oc.env:REINFLOW_DATA_DIR}/robomimic/${env_name}-img/normalization.npz
seed: 42
device: cuda:0
sim_device: cuda:0
###############################
denoising_steps: 5  # MeanFlow typically uses 5 inference steps
ft_denoising_steps: 5
min_std: 0.05
max_std: 0.12
###############################
env:
  n_envs: 14
  name: ${env_name}
  best_reward_threshold_for_success: 1
  max_episode_steps: 800
  save_video: false
  use_image_obs: true
  wrappers:
    robomimic_image:
      normalization_path: ${normalization_path}
      low_dim_keys:
      - robot0_eef_pos
      - robot0_eef_quat
      - robot0_gripper_qpos
      - robot1_eef_pos
      - robot1_eef_quat
      - robot1_gripper_qpos
      image_keys:
      - shouldercamera0_image
      - shouldercamera1_image
      shape_meta: ${shape_meta}
    multi_step:
      n_obs_steps: ${cond_steps}
      n_action_steps: ${act_steps}
      max_episode_steps: ${env.max_episode_steps}
      reset_within_step: true
shape_meta:
  obs:
    rgb:
      shape: [6,96,96]  # 2 cameras × 3 channels
    state:
      shape: [18]  # two robots
  action:
    shape: [14]  # two robots
wandb:
  entity: ${oc.env:REINFLOW_WANDB_ENTITY}
  project: DM1-robomimic-${env_name}-finetune
  run: ${now:%Y-%m-%d}_${now:%H-%M-%S}_${name}
  offline_mode: false
train:
  n_train_itr: 301
  n_critic_warmup_itr: 2
  n_steps: 800
  gamma: 0.999
  augment: true
  grad_accumulate: 20
  buffer_device: cpu
  actor_lr: 3.0e-06  # Slightly lower for MeanFlow stability
  actor_weight_decay: 0
  actor_lr_scheduler:
    type: cosine
    first_cycle_steps: 100
    warmup_steps: 10
    min_lr: 3.0e-06
  critic_lr: 4.5e-4
  critic_weight_decay: 0
  critic_lr_scheduler:
    type: cosine
    first_cycle_steps: 100
    warmup_steps: 25
    min_lr: 3e-4
  save_model_freq: 100
  val_freq: 10
  render:
    freq: 1
    num: 0
  reward_scale_running: true
  reward_scale_const: 1.0
  gae_lambda: 0.95
  batch_size: 560
  logprob_batch_size: 560
  update_epochs: 10
  vf_coef: 0.5
  ent_coef: 0.01
  target_kl: 0.01
  lr_schedule: fixed
  repeat_samples: true
  verbose: false
  clip_intermediate_actions: true
  account_for_initial_stochasticity: true
  max_grad_norm: 25.0
  use_bc_loss: true
  bc_loss_type: W2
  bc_loss_coeff: 0.2           # Initial BC loss coefficient
  bc_loss_coeff_final: 0.05    # Final BC loss coefficient after decay
  bc_loss_decay_start: 20      # Start decaying BC loss at iteration 20
  bc_loss_decay_end: 50        # Finish decaying BC loss at iteration 50
model:
  _target_: model.flow.ft_ppo.ppomeanflow.PPOMeanFlow
  device: ${device}
  actor_policy_path: ${base_policy_path}
  ###################################################################
  policy:
    _target_: model.flow.mlp_meanflow.MeanFlowViT
    backbone:
      _target_: model.common.vit.VitEncoder
      obs_shape: ${shape_meta.obs.rgb.shape}
      num_channel: ${eval:'6 * ${img_cond_steps}'}  # 2 cameras
      cfg:
        patch_size: 8
        depth: 1
        embed_dim: 128
        num_heads: 4
        embed_style: embed2
        embed_norm: 0
    action_dim: ${action_dim}
    horizon_steps: ${horizon_steps}
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    img_cond_steps: ${img_cond_steps}
    time_dim: 16
    r_embedding_dim: 16  # MeanFlow specific r parameter embedding
    mlp_dims: [768, 768, 768]
    activation_type: Mish
    out_activation_type: Identity
    use_layernorm: false
    residual_style: true
    spatial_emb: 128
    visual_feature_dim: 128
    dropout: 0.1
    num_img: 2  # 2 cameras for transport task
    augment: false
  ###################################################################
  critic:
    _target_: model.common.critic.ViTCritic
    spatial_emb: 128
    augment: false
    backbone:
      _target_: model.common.vit.VitEncoder
      obs_shape: ${shape_meta.obs.rgb.shape}
      num_channel: ${eval:'6 * ${img_cond_steps}'}  # 2 cameras
      img_h: ${shape_meta.obs.rgb.shape[1]}
      img_w: ${shape_meta.obs.rgb.shape[2]}
      cfg:
        patch_size: 8
        depth: 1
        embed_dim: 128
        num_heads: 4
        embed_style: embed2
        embed_norm: 0
    img_cond_steps: ${img_cond_steps}
    mlp_dims: [256,256,256]
    activation_type: Mish
    residual_style: true
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
  act_dim: ${action_dim}
  horizon_steps: ${horizon_steps}
  act_min: -1
  act_max: 1
  obs_dim: ${obs_dim}
  cond_steps: ${cond_steps}
  noise_scheduler_type: learn
  inference_steps: ${denoising_steps}
  ft_denoising_steps: ${ft_denoising_steps}
  randn_clip_value: 3
  min_sampling_denoising_std: ${min_std}
  min_logprob_denoising_std: ${min_std}
  max_logprob_denoising_std: ${max_std}
  logprob_min: -1.0
  logprob_max: 1.0
  clip_ploss_coef: 0.01
  clip_ploss_coef_base: 0.001
  clip_ploss_coef_rate: 3
  clip_vloss_coef: null
  denoised_clip_value: 1.0
  time_dim_explore: 16
  learn_explore_time_embedding: true
  use_time_independent_noise: false  # MeanFlow uses time-dependent noise
  noise_hidden_dims: [384,384,384]
  logprob_debug_sample: false
  logprob_debug_recalculate: false
  explore_net_activation_type: Tanh
